apiVersion: batch/v1
kind: Job
metadata:
  name: demo-job
  namespace: nginx
spec:
  completions: 1
  parallelism: 1
  backoffLimit: 3
  template:
    metadata:
      labels:
        app: batch-task
    spec:
      containers:
        - name: batch-container
          image: busybox:latest
          command: ["sh", "-c", "echo heyy Abishek && sleep 10"]
      restartPolicy: Never
